import { useEffect, useMemo, useState } from "react";
import { LanguageContext } from "./languageStore";

const translations = {
  en: {},
  hi: {
    "nav.home": "होम",
    "nav.services": "सेवाएँ",
    "nav.properties": "प्रॉपर्टी",
    "nav.testimonials": "ग्राहक अनुभव",
    "nav.profile": "प्रोफ़ाइल",
    "nav.blog": "ब्लॉग",
    "nav.help": "सहायता",
    "nav.helpCenter": "सहायता केंद्र",
    "nav.salesEnquiry": "बिक्री संबंधी पूछताछ",
    "nav.chatWithUs": "हमसे चैट करें",
    "nav.contactUs": "संपर्क करें",
    "nav.free": "निःशुल्क",
    "nav.translate": "भाषा चुनें",
    "nav.closeMenu": "मेनू बंद करें",
    "common.home": "होम",
    "common.breadcrumb": "ब्रेडक्रंब",
    "common.loadingTitle": "आपकी पसंद की प्रॉपर्टी लोड हो रही है...",
    "common.loadingDescription":
      "कृपया प्रतीक्षा करें, हम आपके लिए प्रॉपर्टी विकल्प तैयार कर रहे हैं।",
    "market.updates": "बाज़ार अपडेट",
    "common.contactUs": "संपर्क करें",
    "common.viewDetails": "विवरण देखें",
    "common.viewAll": "सभी देखें",
    "common.share": "शेयर करें",
    "common.edit": "संपादित करें",
    "common.delete": "हटाएँ",
    "common.loading": "लोड हो रहा है...",
    "common.loadingContent": "सामग्री लोड हो रही है...",
    "common.noImage": "चित्र उपलब्ध नहीं है",
    "common.noResults": "कोई परिणाम नहीं मिला",
    "common.readMore": "और पढ़ें",
    "common.submit": "जमा करें",
    "common.submitting": "जमा किया जा रहा है...",
    "common.cancel": "रद्द करें",
    "common.search": "खोजें",
    "common.all": "सभी",
    "common.allLocations": "सभी स्थान",
    "common.allTypes": "सभी प्रकार",
    "common.showing": "दिखाए जा रहे हैं",
    "common.properties": "प्रॉपर्टी",
    "common.property": "प्रॉपर्टी",
    "common.beds": "बेडरूम",
    "common.baths": "बाथरूम",
    "common.features": "खास सुविधाएँ",
    "common.more": "और",
    "common.priceOnRequest": "कीमत के लिए पूछें",
    "common.contactForPrice": "कीमत जानने के लिए संपर्क करें",
    "common.plot": "प्लॉट",
    "common.houseVilla": "मकान/विला",
    "common.corner": "कॉर्नर प्लॉट",
    "common.quickLinks": "त्वरित लिंक",
    "common.clientReviews": "ग्राहक समीक्षाएँ",
    "common.ourServices": "हमारी सेवाएँ",
    "common.allProperties": "सभी प्रॉपर्टी",
    "common.blog": "रियल एस्टेट ब्लॉग",
    "common.getFreeConsultation": "निःशुल्क सलाह लें",
    "sitemap.directory": "वेबसाइट नेविगेशन निर्देशिका",
    "sitemap.title": "Arjun Buildtech साइटमैप",
    "sitemap.description":
      "हमारी वेबसाइट के सभी पेज, प्रॉपर्टी श्रेणियों, सेवा माध्यमों और कानूनी नीतियों पर आसानी से जाएँ।",
    "sitemap.mainPages": "मुख्य पेज",
    "sitemap.exploreProperties": "प्रॉपर्टी देखें",
    "sitemap.realEstateServices": "रियल एस्टेट सेवाएँ",
    "sitemap.legal": "कानूनी जानकारी और नीतियाँ",
    "sitemap.companyProfile": "कंपनी प्रोफ़ाइल",
    "sitemap.investProperties": "रोहतक की प्रॉपर्टी में निवेश करें",
    "sitemap.sellProperty": "रोहतक में प्रॉपर्टी बेचें",
    "sitemap.investmentConsulting": "निवेश परामर्श",
    "sitemap.propertyConsultation": "प्रॉपर्टी परामर्श",
    "sitemap.primeAreas": "हमारे प्रमुख क्षेत्र (सेक्टर और Suncity)",
    "service.professional": "Arjun Buildtech की पेशेवर सेवाएँ",
    "service.getConsultation": "निःशुल्क सलाह लें",
    "service.about": "इस सेवा के बारे में",
    "service.benefits": "मुख्य लाभ",
    "service.faq": "अक्सर पूछे जाने वाले सवाल",
    "service.ready": "शुरू करने के लिए तैयार हैं?",
    "service.inquiryCopy":
      "हमारा छोटा पूछताछ फ़ॉर्म भरें। रोहतक में हमारे रियल एस्टेट विशेषज्ञ जल्द आपसे संपर्क करेंगे।",
    "service.inquireNow": "अभी पूछताछ करें",
    "service.callDirect": "या सीधे हमें कॉल करें:",
    "home.quickLinks": "त्वरित लिंक",
    "home.loading": "सामग्री लोड हो रही है...",
    "footer.contactInfo": "संपर्क जानकारी",
    "footer.contactNumbers": "संपर्क नंबर",
    "footer.officeLocations": "कार्यालय के पते",
    "footer.businessHours": "कार्यालय समय",
    "footer.allDays": "सप्ताह के सभी 7 दिन उपलब्ध",
    "footer.ready": "अपनी पसंद की प्रॉपर्टी ढूँढ़ने के लिए तैयार हैं?",
    "footer.governmentLinks": "सरकारी और उपयोगी लिंक",
    "footer.propertiesRohtak": "रोहतक में प्रॉपर्टी",
    "footer.rights": "सर्वाधिकार सुरक्षित।",
    "footer.madeManaged": "निर्माण और प्रबंधन:",
    "footer.privacy": "गोपनीयता नीति",
    "footer.terms": "सेवा की शर्तें",
    "footer.sitemap": "साइटमैप",
    "property.findDream": "{location} में अपनी पसंद की प्रॉपर्टी खोजें",
    "property.explore":
      "{location} में बेहतरीन रिहायशी और कमर्शियल प्रॉपर्टी देखें",
    "property.in": "में प्रॉपर्टी",
    "property.forSale": "बिक्री के लिए",
    "property.noImage": "चित्र उपलब्ध नहीं है",
    "property.showing": "{location} में बिक्री के लिए {type}: {count}",
    "contact.heading": "प्रॉपर्टी की सही सलाह पाएँ",
    "contact.description":
      "रोहतक के अनुभवी रियल एस्टेट सलाहकारों से बात करें। हम आपकी पसंद की प्रॉपर्टी के लिए बेहतर सौदा पाने में मदद करेंगे।",
    "contact.name": "आपका नाम*",
    "contact.email": "आपका ईमेल*",
    "contact.phone": "फ़ोन नंबर*",
    "contact.location": "आपका स्थान*",
    "contact.message": "आपका संदेश*",
    "contact.consent":
      "मैं अपनी पूछताछ का जवाब पाने के लिए अपनी जानकारी संग्रहीत करने की सहमति देता/देती हूँ और Arjun Buildtech विशेषज्ञों से संपर्क किए जाने पर सहमत हूँ।",
    "contact.success":
      "संदेश सफलतापूर्वक भेज दिया गया! हम 24 घंटे के भीतर आपसे संपर्क करेंगे।",
    "contact.error": "फ़ॉर्म भेजने में त्रुटि हुई। कृपया फिर से प्रयास करें।",
    "contact.getConsultation": "निःशुल्क सलाह लें",
    "home.heroSubtitle":
      "रोहतक में भरोसेमंद प्रॉपर्टी सलाहकारों के साथ अपना पसंदीदा लग्ज़री विला, रिहायशी प्लॉट या बेहतर रिटर्न वाला निवेश पाएँ।",
    "home.leadingRealEstate": "रोहतक में अग्रणी रियल एस्टेट सेवा",
    "home.featuredTitle": "चुनिंदा प्रॉपर्टी",
    "home.featuredDescription":
      "HSVP प्लॉट, लग्ज़री विला और निवेश के लिए तैयार कमर्शियल प्रॉपर्टी का हमारा खास चयन देखें।",
    "home.seeAllProperties": "सभी प्रॉपर्टी देखें",
    "home.noFeatured": "अभी कोई चुनिंदा प्रॉपर्टी उपलब्ध नहीं है",
    "home.updatingListings":
      "हम अपनी प्रीमियम लिस्टिंग अपडेट कर रहे हैं। कृपया बाद में फिर देखें।",
    "home.newProperties": "रोहतक में नई प्रॉपर्टी",
    "home.newPropertiesDescription":
      "हाल ही में जोड़ी गई प्रॉपर्टी और खास रियल एस्टेट अवसर देखें।",
    "home.allListings": "सभी लिस्टिंग देखें",
    "home.quickLinksTitle": "त्वरित लिंक",
    "home.propertiesRohtak": "रोहतक में प्रॉपर्टी",
    "footer.about":
      "यदि आप अपने सपनों का प्लॉट, लग्ज़री विला या बेहतर रिटर्न वाले निवेश के लिए प्रॉपर्टी सलाहकार ढूँढ़ रहे हैं, तो आप सही जगह पर हैं। Arjun Buildtech रोहतक, हरियाणा के अग्रणी रियल एस्टेट सलाहकारों में से एक है। हमारा उद्देश्य ग्राहकों की ज़रूरत के अनुसार बेहतरीन गुणवत्ता और योजना देना है।",
    "footer.quickLinks": "त्वरित लिंक",
    "card.noImage": "चित्र उपलब्ध नहीं है",
    "card.plot": "प्लॉट",
    "card.property": "प्रॉपर्टी",
    "card.houseVilla": "मकान/विला",
    "card.corner": "कॉर्नर प्लॉट",
    "card.priceOnRequest": "कीमत के लिए पूछें",
    "card.viewDetails": "विवरण देखें",
    "card.share": "शेयर करें",
    "card.beds": "बेडरूम",
    "card.baths": "बाथरूम",
    "card.features": "खास सुविधाएँ:",
    "card.more": "और",
    "card.copied": "लिंक कॉपी हो गया!",
    "card.premiumProperty": "प्रीमियम प्रॉपर्टी",
    "contact.formTitle": "प्रॉपर्टी की सही सलाह पाएँ",
    "contact.formDescription":
      "रोहतक के अनुभवी रियल एस्टेट सलाहकारों से बात करें। हम आपकी पसंद की प्रॉपर्टी के लिए बेहतर सौदा पाने में मदद करेंगे।",
    "property.allTypes": "सभी प्रकार",
    "property.house": "मकान",
    "property.villa": "विला",
    "property.plot": "प्लॉट",
    "property.flat": "फ्लैट",
    "property.commercial": "कमर्शियल",
    "property.noResults": "कोई प्रॉपर्टी नहीं मिली",
    "property.noResultsDescription":
      "{location} में चुने गए फ़िल्टर से मेल खाने वाली कोई लिस्टिंग नहीं मिली। स्थान या प्रॉपर्टी का प्रकार बदलकर देखें।",
    "property.resetFilters": "फ़िल्टर रीसेट करें",
    "property.marketTitle": "{location} का रियल एस्टेट बाज़ार",
    "property.marketDescription":
      "{location} हरियाणा के सबसे पसंदीदा रियल एस्टेट क्षेत्रों में से एक है। सुनियोजित सेक्टर, बेहतर सड़क संपर्क और तेज़ कमर्शियल विकास इसे निवेश के लिए आकर्षक बनाते हैं। HSVP रिहायशी प्लॉट, बिल्डर फ्लोर या कमर्शियल जगह के लिए Arjun Buildtech कानूनी जाँच और पूरी प्रक्रिया में मार्गदर्शन देता है।",
    "property.verifiedTitles": "100% सत्यापित दस्तावेज़",
    "property.verificationDescription":
      "हर प्रॉपर्टी लिस्टिंग की कानूनी जाँच की जाती है।",
    "property.primeLocations": "प्रमुख स्थान",
    "property.primeDescription":
      "सेक्टर 1, 27 और Suncity टाउनशिप पर विशेष ध्यान।",
    "property.directAssistance": "सीधी सहायता",
    "property.directDescription":
      "स्थानीय प्रॉपर्टी विशेषज्ञों से सीधे बात करें।",
    "property.lookingMore": "{location} में और प्रॉपर्टी देख रहे हैं?",
    "property.contactDescription":
      "व्यक्तिगत प्रॉपर्टी सुझाव पाने और रोहतक में बेहतर सौदे के लिए हमारे रियल एस्टेट विशेषज्ञों से संपर्क करें।",
    "property.contactAgent": "एजेंट से संपर्क करें",
    "common.in": "में",
    "card.sharePrompt": "इस प्रॉपर्टी को देखें:",
    "detail.loading": "प्रॉपर्टी का विवरण लोड हो रहा है...",
    "detail.notFound": "प्रॉपर्टी नहीं मिली",
    "detail.notFoundDescription":
      "आप जिस प्रॉपर्टी को देख रहे हैं, वह हटाई जा चुकी हो सकती है या अब उपलब्ध नहीं है।",
    "detail.title": "प्रॉपर्टी का विवरण",
    "detail.compassAlt": "दिशासूचक चित्र",
    "help.title": "सहायता केंद्र",
    "help.intro":
      "अक्सर पूछे जाने वाले सवालों के जवाब पाएँ, हमारी प्रक्रिया जानें और समझें कि Arjun Buildtech आपकी प्रॉपर्टी खरीदने में कैसे मदद कर सकता है।",
    "help.faqHeading": "अक्सर पूछे जाने वाले सवाल",
    "help.faq1q": "प्रॉपर्टी देखने का समय कैसे तय करें?",
    "help.faq1a":
      "बिक्री पूछताछ फ़ॉर्म भरें या हमें फ़ोन करें। हमारी टीम आपकी सुविधा के अनुसार समय तय करेगी।",
    "help.faq2q": "प्रॉपर्टी खरीदने के लिए कौन से कानूनी दस्तावेज़ चाहिए?",
    "help.faq2a":
      "आमतौर पर वैध पहचान पत्र, PAN कार्ड, पते का प्रमाण और पासपोर्ट आकार की तस्वीरें चाहिए। प्रॉपर्टी के अनुसार NDC और पुराने रजिस्ट्री दस्तावेज़ भी जाँचे जाते हैं।",
    "help.faq3q": "क्या आप होम लोन में सहायता करते हैं?",
    "help.faq3a":
      "हाँ, हम प्रमुख बैंकों और वित्तीय संस्थानों के साथ मिलकर उपयुक्त ब्याज दर और तेज़ प्रक्रिया वाला होम लोन पाने में मदद करते हैं।",
    "help.faq4q": "मैं अपनी प्रॉपर्टी बिक्री के लिए कैसे सूचीबद्ध करूँ?",
    "help.faq4a":
      "संपर्क पेज के ज़रिए हमारी टीम से बात करें या सहायता नंबर पर कॉल करें। हम प्रॉपर्टी का मूल्यांकन करके उसे अपने प्रमुख माध्यमों पर सूचीबद्ध करेंगे।",
    "help.stillNeed": "अभी भी मदद चाहिए?",
    "help.stillNeedCopy":
      "अगर आपके सवाल का जवाब यहाँ नहीं मिला, तो हमारी सहायता टीम आपकी मदद के लिए तैयार है।",
    "help.contactSupport": "सहायता से संपर्क करें",
    "sales.title": "बिक्री संबंधी पूछताछ",
    "sales.intro":
      "खरीदने, बेचने या निवेश करने में रुचि है? नीचे फ़ॉर्म भरें। हमारी टीम आपकी ज़रूरत के अनुसार प्रॉपर्टी विकल्प लेकर आपसे संपर्क करेगी।",
    "sales.submitDetails": "अपनी जानकारी भेजें",
    "sales.directLine": "सीधी बिक्री लाइन",
    "sales.callCopy": "तुरंत बात करना चाहते हैं? हमारी बिक्री टीम को कॉल करें।",
    "sales.whyChoose": "Arjun Buildtech क्यों चुनें?",
    "sales.verified": "पूरी तरह सत्यापित प्रॉपर्टी और पारदर्शी कीमतें।",
    "sales.legal": "कानूनी जाँच और दस्तावेज़ीकरण में विशेषज्ञ मार्गदर्शन।",
    "sales.local": "रोहतक और NCR के स्थानीय बाज़ार की गहरी जानकारी।",
    "chat.title": "हमसे चैट करें",
    "chat.intro":
      "अपने सवालों के तुरंत जवाब पाएँ। अपनी पसंद के मैसेजिंग प्लेटफ़ॉर्म पर हमारे प्रॉपर्टी विशेषज्ञों से जुड़ें।",
    "chat.whatsappSupport": "WhatsApp सहायता",
    "chat.online":
      "हमारे विशेषज्ञ ऑनलाइन हैं और प्रॉपर्टी के विवरण, साइट विज़िट और कीमत में मदद के लिए तैयार हैं।",
    "chat.startWhatsApp": "WhatsApp चैट शुरू करें",
    "chat.sendMessage": "हमें संदेश भेजें",
    "chat.formCopy":
      "विस्तार से पूछताछ भेजना चाहते हैं? संपर्क फ़ॉर्म भरें; हम ईमेल से जवाब देंगे।",
    "chat.openForm": "संपर्क फ़ॉर्म खोलें",
    "notFound.title": "ओह! पेज नहीं मिला",
    "notFound.copy":
      "आप जिस पेज को ढूँढ़ रहे हैं, वह मौजूद नहीं है। आपको कुछ ही देर में होमपेज पर भेज दिया जाएगा।",
    "chatbot.greeting":
      "नमस्ते! क्या आप रोहतक में प्रीमियम प्रॉपर्टी ढूँढ़ रहे हैं? HSVP और Suncity सेक्टर में बेहतर विकल्प खोजने में मैं आपकी मदद कर सकता हूँ। आज मैं आपकी कैसे सहायता करूँ?",
    "chatbot.whatsappUs": "हमें व्हाट्सएप करें",
    "chatbot.raiseQuery": "अपना प्रश्न उठाएँ",
    "chatbot.helloText":
      "नमस्कार! बस नीचे क्लिक करें और अपना प्रश्न टाइप करें।",
    "chatbot.expertsReply": "हमारे विशेषज्ञ आपको शीघ्र ही उत्तर देंगे।",
    "chatbot.clickToChat": "चैट करने के लिए यहां क्लिक करें",
    "chatbot.parveen": "अर्जुन बिल्डटेक प्रॉपर्टीज",
    "chatbot.quickShortcuts": "त्वरित संदेश:",
    "chatbot.plot": "मैं रिहायशी प्लॉट ढूँढ़ रहा/रही हूँ",
    "chatbot.house": "मैं घर खरीदना चाहता/चाहती हूँ",
    "chatbot.sell": "मेरे पास बेचने के लिए प्रॉपर्टी है",
    "chatbot.investment": "मुझे निवेश संबंधी सलाह चाहिए",
    "chatbot.repliesMinutes": "आमतौर पर कुछ मिनटों में जवाब देते हैं",
    "chatbot.callNow": "अभी कॉल करें",
    "chatbot.close": "बंद करें",
    "chatbot.message": "संदेश...",
    "homeSearch.location": "स्थान",
    "homeSearch.status": "स्थिति",
    "homeSearch.type": "प्रकार",
    "homeSearch.any": "कोई भी",
    "homeSearch.forSale": "बिक्री के लिए",
    "homeSearch.investment": "निवेश",
    "homeSearch.search": "खोजें",
    "services.heading": "हमारी रियल एस्टेट सेवाएँ देखें",
    "services.description":
      "रोहतक में खरीदने-बेचने से लेकर निवेश सलाह तक, प्रॉपर्टी से जुड़ी पूरी सहायता।",
    "services.readMore": "और पढ़ें",
    "services.invest.title": "रोहतक की प्रॉपर्टी में निवेश करें",
    "services.invest.description":
      "रोहतक में सूचीबद्ध रिहायशी प्लॉट और घर देखें। उपलब्धता और संपत्ति की जानकारी हर लिस्टिंग के अनुसार अलग हो सकती है।",
    "services.sell.title": "रोहतक में प्रॉपर्टी बेचें",
    "services.sell.description":
      "अपनी संपत्ति, अपेक्षित कीमत और बिक्री के लिए ज़रूरी जानकारी पर चर्चा करें।",
    "services.investment.title": "निवेश परामर्श",
    "services.investment.description":
      "खरीद पर विचार करते समय लोकेशन, उपयोग, कीमत, दस्तावेज़ और जारी खर्चों की तुलना करें।",
    "services.consult.title": "प्रॉपर्टी परामर्श",
    "services.consult.description":
      "अपनी ज़रूरत, बजट और उपयोग के अनुसार उपलब्ध संपत्ति विकल्पों की तुलना करें।",
    "services.areas.title": "हमारे प्रमुख क्षेत्र",
    "services.areas.description":
      "वर्तमान रोहतक लिस्टिंग को लोकेशन के अनुसार देखें और किसी विशेष अनुरोध के लिए हमसे संपर्क करें।",
    "profile.title": "कंपनी प्रोफ़ाइल",
    "profile.intro":
      "अगर आप अपने सपनों का प्लॉट, लग्ज़री विला या बेहतर रिटर्न वाला निवेश पाने के लिए भरोसेमंद प्रॉपर्टी सलाहकार ढूँढ़ रहे हैं, तो आप सही जगह पर हैं। रोहतक, हरियाणा की अग्रणी रियल एस्टेट सलाहकार संस्था के रूप में, हम सुरक्षित और लाभकारी निवेश के लिए एक दशक से अधिक का बाज़ार अनुभव देते हैं।",
    "profile.prime": "प्रमुख रियल एस्टेट",
    "profile.primeCopy":
      "रोहतक में HSVP सेक्टर, Suncity और प्रीमियम कमर्शियल प्रॉपर्टी में विशेषज्ञता।",
    "profile.advisory": "निवेश सलाह",
    "profile.advisoryCopy":
      "निवेश पर बेहतर रिटर्न और दीर्घकालिक मूल्य बढ़ाने के लिए आपकी ज़रूरत के अनुसार रणनीति।",
    "profile.transparency": "पूरी पारदर्शिता",
    "profile.transparencyCopy":
      "स्पष्ट दस्तावेज़, पूरी कानूनी जाँच और शुरू से अंत तक दस्तावेज़ी सहायता।",
    "profile.portfolio": "हमारा पोर्टफोलियो",
    "profile.directory": "संपर्क सूची",
    "profile.personnel": "प्रमुख कर्मचारी",
    "profile.offices": "हमारे कार्यालय",
    "profile.headOffice": "मुख्य कार्यालय",
    "profile.branchOffice": "शाखा कार्यालय",
    "profile.email": "ईमेल पता",
    "profile.eyebrow": "रोहतक, हरियाणा में रियल एस्टेट सलाहकार",
    "profile.breadcrumb": "Arjun Buildtech प्रोफ़ाइल",
    "profile.contactAction": "संपर्क करें",
    "profile.browseAction": "प्रॉपर्टी देखें",
    "profile.aboutHeading": "Arjun Buildtech के बारे में",
    "profile.aboutCopy":
      "Arjun Buildtech रोहतक, हरियाणा में प्रॉपर्टी सलाह और रियल एस्टेट सेवाएँ देता है। हमारी टीम HSVP और Suncity के रिहायशी प्लॉट, विला और कमर्शियल प्रॉपर्टी में खरीदारों को विकल्प समझने, दस्तावेज़ जाँचने और आगे की प्रक्रिया में मार्गदर्शन देती है।",
    "profile.focusHeading": "हमारी विशेषज्ञता",
    "profile.focusPlots": "रिहायशी प्लॉट",
    "profile.focusVillas": "विला और घर",
    "profile.focusCommercial": "कमर्शियल प्रॉपर्टी",
    "profile.focusAdvice": "निवेश और प्रॉपर्टी सलाह",
    "profile.areasHeading": "रोहतक में सेवा क्षेत्र",
    "profile.areaSectors": "HSVP सेक्टर 1, 2, 3, 25 और 27",
    "profile.areaSuncity": "Suncity सेक्टर 34, 35, 36 और 36A",
    "profile.portfolioDescription": "Arjun Buildtech की ब्रोशर सामग्री देखें।",
    "profile.contactHeading": "टीम से संपर्क करें",
    "profile.contactDescription":
      "प्रॉपर्टी, साइट विज़िट या निवेश संबंधी सवालों के लिए हमारी टीम से बात करें।",
    "profile.emailUs": "ईमेल करें",
    "profile.directCall": "फ़ोन करें",
    "profile.leadership": "नेतृत्व टीम",
    "home.faqTitle": "अक्सर पूछे जाने वाले सवाल",
    "home.faqIntro":
      "रोहतक में हमारी रियल एस्टेट सेवाओं, प्रॉपर्टी लिस्टिंग और कानूनी प्रक्रिया से जुड़े आम सवालों के जवाब पाएँ।",
    "home.faq1q": "Arjun Buildtech कौन-सी सेवाएँ देता है?",
    "home.faq1a":
      "हम रोहतक, हरियाणा में प्रॉपर्टी बेचने और निवेश करने में ग्राहकों की मदद के लिए प्रॉपर्टी परामर्श और रियल एस्टेट सेवाएँ देते हैं।",
    "home.faq2q": "Arjun Buildtech कहाँ स्थित है?",
    "home.faq2a":
      "हमारा व्यावसायिक पता सेक्टर 27 और सेक्टर 1, रोहतक, हरियाणा 124001 है। आने से पहले संपर्क कर उचित स्थान की पुष्टि करें।",
    "home.faq3q": "क्या आप प्रॉपर्टी निवेश की योजना बनाने में मदद करते हैं?",
    "home.faq3a":
      "हम आपके लक्ष्य पर चर्चा कर उपलब्ध संपत्ति की जानकारी की तुलना करने में मदद कर सकते हैं। भविष्य की कीमत या रिटर्न की गारंटी नहीं होती।",
    "home.faq4q":
      "क्या मैं Arjun Buildtech के ज़रिए अपनी प्रॉपर्टी बिक्री के लिए सूचीबद्ध कर सकता/सकती हूँ?",
    "home.faq4a":
      "लिस्टिंग प्रक्रिया, ज़रूरी संपत्ति जानकारी और लागू शर्तों पर चर्चा करने के लिए हमसे संपर्क करें।",
    "home.faq5q": "आप किस तरह की प्रॉपर्टी में काम करते हैं?",
    "home.faq5a":
      "संपत्ति के प्रकार उपलब्धता के अनुसार बदलते हैं। रोहतक में प्लॉट, घर और कमर्शियल विकल्पों के लिए वर्तमान लिस्टिंग देखें।",
    "home.faq6q":
      "क्या आप प्रॉपर्टी के दस्तावेज़ और रजिस्ट्रेशन में मदद करते हैं?",
    "home.faq6a":
      "हम लिस्टिंग में उपलब्ध जानकारी समझने और अगले कदमों पर चर्चा करने में मदद कर सकते हैं। संपत्ति के दस्तावेज़ योग्य कानूनी विशेषज्ञ से स्वतंत्र रूप से जाँचें।",
    "home.faq7q": "Arjun Buildtech से संपर्क कैसे करें?",
    "home.faq7a":
      "हमें +91 93504 47531 पर कॉल करें या arjun.buildtech27@gmail.com पर ईमेल करें। वेबसाइट के संपर्क फ़ॉर्म से भी पूछताछ भेज सकते हैं।",
    "home.whyTitle": "Arjun Buildtech को क्यों चुनें?",
    "home.whyIntro":
      "रोहतक के भरोसेमंद रियल एस्टेट विशेषज्ञों के रूप में, हम ग्राहकों को प्रीमियम रिहायशी प्लॉट और घर बेचने या उनमें निवेश करने में मदद करते हैं।",
    "home.reason1.title": "रोहतक के स्थानीय विशेषज्ञ",
    "home.reason1.copy":
      "हम केवल रोहतक पर ध्यान देते हैं और HSVP तथा Suncity सेक्टर की गहरी जानकारी के आधार पर सही प्रॉपर्टी खोजने में मदद करते हैं।",
    "home.reason2.title": "खरीदारों और विक्रेताओं के लिए सहायता",
    "home.reason2.copy":
      "बिक्री या खरीद के लिए लिस्टिंग प्रक्रिया, विकल्पों की तुलना और अगले कदम समझने में सहायता पाएँ।",
    "home.reason3.title": "संपत्ति की जानकारी की तुलना करें",
    "home.reason3.copy":
      "हर लिस्टिंग में उपलब्ध लोकेशन, कीमत, आकार और सुविधाएँ देखें और साइट विज़िट से पहले सवाल पूछें।",
    "home.reason4.title": "हर ग्राहक के लिए व्यक्तिगत सहायता",
    "home.reason4.copy":
      "हमारी टीम आपकी प्रॉपर्टी की ज़रूरत, बजट और लक्ष्यों के अनुसार सहायता देती है।",
    "market.title": "आपकी रियल एस्टेट मार्गदर्शिका",
    "market.industry": "बाज़ार की जानकारी",
    "market.legal": "कानूनी अपडेट",
    "market.seeAll": "सभी देखें",
    "market.readArticle": "लेख पढ़ें",
    "market.exploreServices": "सेवाएँ देखें",
    "localities.explore": "देखें",
    "localities.popular": "लोकप्रिय क्षेत्र",
    "localities.inRohtak": "रोहतक में",
    "localities.reviews": "समीक्षाएँ",
    "localities.propertiesForSale": "प्रॉपर्टी बिक्री के लिए",
    "reviews.empty": "अभी कोई समीक्षा नहीं है।",
    "reviews.write": "समीक्षा लिखें",
    "reviews.title": "हमारे ग्राहक क्या कहते हैं",
    "reviews.description":
      "रोहतक के प्रॉपर्टी खरीदारों और विक्रेताओं की असली राय। हम पारदर्शिता और सत्यापित ग्राहकों की प्रामाणिक समीक्षाओं को महत्व देते हैं।",
    "reviews.basedOn": "{count} समीक्षाओं के आधार पर",
    "reviews.verifiedClient": "सत्यापित ग्राहक",
    "reviews.success": "समीक्षा सफलतापूर्वक भेज दी गई!",
    "reviews.error": "समीक्षा भेजी नहीं जा सकी।",
    "reviews.more": "और समीक्षाएँ देखें",
    "reviews.name": "आपका नाम",
    "reviews.namePlaceholder": "अपना पूरा नाम लिखें",
    "reviews.location": "स्थान",
    "reviews.locationPlaceholder": "उदाहरण: सेक्टर 27, रोहतक",
    "reviews.rating": "रेटिंग",
    "reviews.feedback": "आपकी राय",
    "reviews.feedbackPlaceholder":
      "Arjun Buildtech के साथ अपना अनुभव साझा करें...",
    "reviews.closeForm": "समीक्षा फ़ॉर्म बंद करें",
    "reviews.modalIntro": "हमारी टीम के साथ अपना अनुभव साझा करें",
    "reviews.star": "स्टार",
    "reviews.submitting": "समीक्षा भेजी जा रही है...",
    "reviews.submit": "समीक्षा भेजें",
    "legal.backHome": "होम पर वापस जाएँ",
    "privacy.title": "गोपनीयता नीति",
    "privacy.intro":
      "Arjun Buildtech में आपका स्वागत है। हम आपकी गोपनीयता का सम्मान करते हैं और आपके व्यक्तिगत डेटा की सुरक्षा के लिए प्रतिबद्ध हैं। यह नीति बताती है कि वेबसाइट देखने या हमारी रियल एस्टेट सेवाओं का उपयोग करने पर हम आपकी जानकारी कैसे एकत्र, उपयोग और सुरक्षित रखते हैं।",
    "privacy.section1": "1. हम कौन-सी जानकारी एकत्र करते हैं",
    "privacy.body1":
      "पूछताछ फ़ॉर्म भरने, न्यूज़लेटर की सदस्यता लेने या हमारे एजेंटों से संपर्क करने पर हम आपका नाम, ईमेल पता, फ़ोन नंबर और प्रॉपर्टी संबंधी पसंद जैसी व्यक्तिगत जानकारी एकत्र कर सकते हैं।",
    "privacy.section2": "2. हम आपकी जानकारी का उपयोग कैसे करते हैं",
    "privacy.body2":
      "हम एकत्र की गई जानकारी का उपयोग इन उद्देश्यों के लिए करते हैं:",
    "privacy.use1": "आपको आपकी ज़रूरत के अनुसार रियल एस्टेट सुझाव देना।",
    "privacy.use2": "आपकी पूछताछ और सहायता अनुरोधों का जवाब देना।",
    "privacy.use3":
      "रोहतक में नई प्रॉपर्टी, प्लॉट और विला के बारे में अपडेट भेजना।",
    "privacy.use4":
      "उपयोगकर्ताओं की प्रतिक्रिया के आधार पर वेबसाइट और सेवाओं को बेहतर बनाना।",
    "privacy.section3": "3. डेटा सुरक्षा",
    "privacy.body3":
      "हम आपकी व्यक्तिगत जानकारी को अनधिकृत पहुँच, बदलाव, खुलासे या नष्ट होने से बचाने के लिए उचित सुरक्षा उपाय अपनाते हैं। फिर भी, इंटरनेट पर जानकारी भेजने का कोई भी तरीका पूरी तरह सुरक्षित नहीं होता।",
    "privacy.section4": "4. जानकारी साझा करना",
    "privacy.body4":
      "हम आपकी व्यक्तिगत पहचान बताने वाली जानकारी दूसरों को नहीं बेचते, न उसका व्यापार करते हैं और न किराये पर देते हैं। हम अपने व्यावसायिक साझेदारों और विश्वसनीय सहयोगियों के साथ ऐसी सामान्य, समेकित जनसांख्यिकीय जानकारी साझा कर सकते हैं जो किसी व्यक्ति की पहचान से जुड़ी न हो।",
    "privacy.section5": "5. हमसे संपर्क करें",
    "privacy.body5":
      "इस गोपनीयता नीति के बारे में कोई सवाल हो, तो इन संपर्क विवरणों पर हमसे बात करें:",
    "privacy.phone": "फ़ोन:",
    "privacy.office": "कार्यालय:",
    "terms.title": "सेवा की शर्तें",
    "terms.intro":
      "Arjun Buildtech में आपका स्वागत है। हमारी वेबसाइट और रियल एस्टेट सेवाओं का उपयोग करके आप नीचे दी गई सेवा की शर्तों से सहमत होते हैं। कृपया इन्हें ध्यान से पढ़ें।",
    "terms.section1": "1. दी जाने वाली सेवाएँ",
    "terms.body1":
      "Arjun Buildtech रोहतक, हरियाणा में रिहायशी प्लॉट, लग्ज़री विला और कमर्शियल प्रॉपर्टी खरीदने, बेचने तथा उनमें निवेश करने से जुड़ी रियल एस्टेट परामर्श सेवाएँ देता है। प्रॉपर्टी का विवरण, उपलब्धता और कीमत बिना पूर्व सूचना के बदल सकती है।",
    "terms.section2": "2. जानकारी की सटीकता",
    "terms.body2":
      "हम वेबसाइट की जानकारी को सही और अद्यतन रखने का प्रयास करते हैं, लेकिन उसकी पूर्णता, विश्वसनीयता या सटीकता की गारंटी नहीं देते। प्रॉपर्टी लिस्टिंग सामान्य जानकारी के लिए है और इसे बाध्यकारी प्रस्ताव नहीं माना जाएगा।",
    "terms.section3": "3. ग्राहक की ज़िम्मेदारियाँ",
    "terms.body3":
      "किसी भी आर्थिक प्रतिबद्धता से पहले प्रॉपर्टी के कानूनी स्वामित्व, ज़ोनिंग और भौतिक स्थिति सहित सभी जानकारी की जाँच करना ग्राहक की ज़िम्मेदारी है। प्रॉपर्टी दस्तावेज़ों या भौतिक स्थिति में अंतर के कारण हुए नुकसान के लिए Arjun Buildtech उत्तरदायी नहीं है।",
    "terms.section4": "4. तृतीय-पक्ष लिंक",
    "terms.body4":
      "हमारी वेबसाइट पर तृतीय-पक्ष वेबसाइटों के लिंक हो सकते हैं, जैसे प्रॉपर्टी की स्थिति जाँचने वाले सरकारी पोर्टल। ये लिंक आपकी सुविधा के लिए दिए गए हैं। उन वेबसाइटों की सामग्री पर हमारा नियंत्रण नहीं है और हम उसके लिए ज़िम्मेदारी नहीं लेते।",
    "terms.section5": "5. शर्तों में बदलाव",
    "terms.body5":
      "हम किसी भी समय इन सेवा शर्तों में बदलाव कर सकते हैं। बदलाव इसी पेज पर प्रकाशित किए जाएँगे। बदलाव के बाद भी हमारी सेवाओं का उपयोग जारी रखना नई शर्तों की स्वीकृति माना जाएगा।",
    "inquiry.verified": "सत्यापित और भरोसेमंद रियल एस्टेट विशेषज्ञ",
    "inquiry.received": "आपका अनुरोध मिल गया",
    "inquiry.followup":
      "हमारे रियल एस्टेट विशेषज्ञ जल्द ही प्रॉपर्टी के विशेष विवरण के साथ आपसे संपर्क करेंगे।",
    "inquiry.done": "हो गया",
    "inquiry.quoteHeading": "तुरंत बेहतर कोटेशन पाएँ",
    "inquiry.name": "अपना नाम लिखें*",
    "inquiry.phone": "मोबाइल नंबर लिखें*",
    "inquiry.requirement": "ज़रूरत चुनें*",
    "inquiry.message": "कोई खास ज़रूरत? (वैकल्पिक)",
    "inquiry.submit": "प्रॉपर्टी के विशेष विवरण पाएँ",
    "inquiry.disclaimer":
      "फ़ॉर्म भेजकर आप Arjun Buildtech के साथ अपनी जानकारी साझा करने की सहमति देते हैं।",
    "smartLead.continueWith": "Arjun Buildtech के साथ आगे बढ़ें",
    "smartLead.title": "क्या आप रोहतक में प्रॉपर्टी ढूँढ़ रहे हैं?",
    "smartLead.copy":
      "WhatsApp पर तुरंत अपनी ज़रूरत के अनुसार प्रॉपर्टी सुझाव पाएँ।",
    "smartLead.name": "आपका नाम",
    "smartLead.phone": "अपना मोबाइल नंबर लिखें",
    "smartLead.continue": "जारी रखें",
    "smartLead.consent":
      "जारी रखकर आप WhatsApp पर प्रॉपर्टी अपडेट पाने के लिए सहमत होते हैं।",
    "smartLead.saved": "नंबर सेव हो गया!",
    "smartLead.followup": "हमारे विशेषज्ञ जल्द ही आपको विवरण भेजेंगे।",
    "newsletter.title": "अपने इनबॉक्स में बाज़ार अपडेट पाएँ",
    "newsletter.copy":
      "रोहतक के रियल एस्टेट रुझान, कीमतों में गिरावट और खास प्लॉट अवसरों की जानकारी पाएँ।",
    "newsletter.success": "सदस्यता सफल रही!",
    "newsletter.email": "अपना ईमेल पता लिखें",
    "newsletter.subscribe": "अभी सदस्यता लें",
    "newsletter.invalidEmail": "कृपया मान्य ईमेल पता लिखें।",
    "newsletter.error": "कुछ गड़बड़ हुई। कृपया बाद में फिर प्रयास करें।",
    "contactInfo.title": "संपर्क करें",
    "contactInfo.description":
      "पूछताछ, साइट विज़िट या प्रॉपर्टी सलाह के लिए हमारे विशेषज्ञों से बात करें। हम आपकी मदद के लिए यहाँ हैं।",
    "contactInfo.locations": "हमारे पते",
    "contactInfo.call": "हमें कॉल करें",
    "contactInfo.email": "ईमेल",
    "contactInfo.hours": "कार्यालय समय",
    "contactInfo.weekdays": "सोमवार–शुक्रवार: सुबह 9–शाम 6",
    "contactInfo.saturday": "शनिवार: सुबह 10–शाम 4",
    "postProperty.title": "क्या आप प्रॉपर्टी खरीदना चाहते हैं?",
    "postProperty.copy":
      "प्रॉपर्टी देखें या सही विकल्प खोजने के लिए {company} से संपर्क करें।",
    "postProperty.browse": "प्रॉपर्टी देखें",
    "blog.breadcrumb": "प्रॉपर्टी समाचार और अपडेट",
    "blog.heading": "रियल एस्टेट समाचार और जानकारी",
    "blog.intro":
      "रोहतक के रियल एस्टेट बाज़ार को आकार देने वाले विशेषज्ञ विश्लेषण, निवेश मार्गदर्शिकाएँ और नई बुनियादी परियोजनाओं के अपडेट पाएँ।",
    "blog.latestNews": "ताज़ा समाचार",
    "blog.search": "लेख खोजें...",
    "blog.noArticles": "कोई लेख नहीं मिला",
    "blog.clearFilters": "सभी फ़िल्टर हटाएँ",
    "blog.featured": "चुनिंदा लेख",
    "blog.shareArticle": "लेख शेयर करें",
    "blog.whatsappShare": "WhatsApp पर शेयर करें",
    "blog.readStory": "पूरी खबर पढ़ें",
    "blog.readMore": "और पढ़ें",
    "blog.loadMore": "और समाचार लोड करें",
    "blog.buyPremium": "प्रीमियम प्रॉपर्टी खरीदें",
    "blog.buyCopy":
      "रोहतक में शहर के भरोसेमंद प्रॉपर्टी डीलर से खास रिहायशी प्लॉट और कमर्शियल ज़मीन देखें।",
    "blog.viewProperties": "उपलब्ध प्रॉपर्टी देखें",
    "blog.trending": "लोकप्रिय विषय",
    "blog.postNotFound": "लेख नहीं मिला",
    "blog.postNotFoundCopy":
      "यह लेख हटाया गया हो सकता है। इसके बजाय बाज़ार के नए अपडेट देखें।",
    "blog.viewMarketUpdates": "सभी बाज़ार अपडेट देखें",
    "blog.reads": "बार पढ़ा गया",
    "blog.readingNow": "अभी पढ़ रहे हैं",
    "blog.minRead": "मिनट पढ़ने का समय",
    "blog.share": "लेख शेयर करें",
    "blog.marketData": "रोहतक बाज़ार डेटा",
    "blog.premierConsultant": "रोहतक के प्रमुख रियल एस्टेट सलाहकार",
    "blog.agencyCopy":
      "हम सेक्टर 27 और सेक्टर 1, रोहतक में चुनिंदा रिहायशी प्लॉट और कमर्शियल प्रॉपर्टी में विशेषज्ञता रखते हैं। पूरी तरह स्वतंत्र और सत्यापित।",
    "blog.ourProperties": "हमारी प्रॉपर्टी देखें",
    "blog.buyPlots": "प्रीमियम प्लॉट खरीदें",
    "blog.noMiddlemen":
      "शहर के भरोसेमंद डीलर से सीधे रोहतक में चुनिंदा रिहायशी प्लॉट और कमर्शियल ज़मीन देखें। कोई बिचौलिया नहीं।",
    "blog.high": "ज़्यादा",
    "blog.primaryProperty": "प्रमुख प्रॉपर्टी",
    "blog.plotsLand": "प्लॉट / ज़मीन",
    "blog.verifiedSeller": "सत्यापित विक्रेता",
    "blog.category.market": "बाज़ार समाचार",
    "blog.category.investment": "निवेश मार्गदर्शिका",
    "blog.category.policy": "नीति अपडेट",
    "blog.category.buying": "खरीद मार्गदर्शिका",
    "blog.category.insights": "बाज़ार की जानकारी",
    "blog.views": "बार पढ़ा गया",
    "blog.liveReaders": "अभी पढ़ रहे हैं",
    "blog.readTime": "मिनट पढ़ने का समय",
    "blog.rohtakData": "रोहतक बाज़ार डेटा",
    "blog.tag.haryana": "हरियाणा रियल एस्टेट",
    "blog.tag.plots": "बिक्री के लिए प्लॉट",
    "blog.marketSeller": "बाज़ार विक्रेता",
    "blog.sectorDemand": "सेक्टर 27 की माँग",
    "detail.emi": "EMI कैलकुलेट करें | 34+ बैंकों से लोन ऑफ़र पाएँ",
    "detail.forRent": "किराये के लिए",
    "detail.forSale": "बिक्री के लिए",
    "detail.beds": "बेडरूम",
    "detail.baths": "बाथरूम",
    "detail.balconies": "बालकनी",
    "detail.cornerPlot": "कॉर्नर प्लॉट",
    "detail.plotArea": "प्लॉट का क्षेत्रफल",
    "detail.superArea": "सुपर एरिया",
    "detail.floor": "मंज़िल",
    "detail.transactionType": "लेन-देन का प्रकार",
    "detail.status": "स्थिति",
    "detail.additionalRooms": "अतिरिक्त कमरे",
    "detail.facing": "मुख दिशा",
    "detail.lift": "लिफ़्ट",
    "detail.furnished": "फर्निशिंग की स्थिति",
    "detail.carParking": "कार पार्किंग",
    "detail.moreDetails": "अधिक जानकारी",
    "detail.priceBreakup": "कीमत का विवरण",
    "detail.bookingAmount": "बुकिंग राशि",
    "detail.carpetArea": "कारपेट एरिया",
    "detail.address": "पता",
    "detail.landmarks": "नज़दीकी पहचान स्थल",
    "detail.furnishing": "फर्निशिंग",
    "detail.flooring": "फ़्लोरिंग",
    "detail.propertyAge": "प्रॉपर्टी की उम्र",
    "detail.construction": "निर्माण की स्थिति",
    "detail.priceTerms": "कीमत की शर्तें",
    "detail.negotiable": "बातचीत संभव",
    "detail.openParking": "ओपन पार्किंग",
    "detail.spaces": "जगहें",
    "detail.ownership": "स्वामित्व का प्रकार",
    "detail.project": "सोसायटी / प्रोजेक्ट",
    "detail.rera": "RERA नंबर",
    "detail.water": "पानी की सुविधा",
    "detail.power": "पावर बैकअप",
    "detail.gas": "गैस कनेक्शन",
    "detail.gated": "गेटेड समुदाय",
    "detail.approval": "अनुमोदन प्राधिकरण",
    "detail.cornerProperty": "कॉर्नर प्रॉपर्टी",
    "detail.yes": "हाँ",
    "detail.roadWidth": "सड़क की चौड़ाई",
    "detail.dimensions": "प्लॉट का माप",
    "detail.boundaryWall": "चारदीवारी",
    "detail.maintenance": "मेंटेनेंस शुल्क",
    "detail.possession": "कब्ज़े की तारीख",
    "detail.pricePer": "प्रति {unit} कीमत",
    "detail.viewAll": "सभी विवरण देखें",
    "detail.description": "विवरण:",
    "detail.defaultDescription": "आपके लिए उपलब्ध एक प्रीमियम प्रॉपर्टी।",
    "detail.highlights": "प्रॉपर्टी की खास बातें",
    "detail.amenities": "लाइफ़स्टाइल सुविधाएँ",
    "detail.contactCompany": "{company} से संपर्क करें",
    "detail.callDirect": "हमें सीधे कॉल करें",
    "detail.callNow": "अभी कॉल करें",
    "detail.shareProperty": "प्रॉपर्टी शेयर करें",
    "detail.verifiedBy": "सत्यापनकर्ता:",
    "detail.similarProjects": "ऐसे ही प्रोजेक्ट की प्रॉपर्टी",
    "detail.priceTrends": "{location} में कीमतों का रुझान",
    "detail.comparableRate": "इस क्षेत्र की तुलनीय दरों का विश्लेषण",
    "detail.projectName": "प्रोजेक्ट का नाम",
    "detail.avgRate": "प्रति वर्ग फुट औसत दर",
    "detail.rentalYield": "किराये से रिटर्न",
    "detail.nearbyResidential": "नज़दीकी रिहायशी क्षेत्र",
    "detail.closerSearch": "आपकी खोज से मिलती-जुलती प्रॉपर्टी",
    "detail.similarSearches": "ऐसी ही खोजें",
    "detail.flatsIn": "{location} में फ्लैट",
    "detail.houseSaleIn": "{location} में बिक्री के लिए मकान",
    "detail.plotsIn": "{location} में प्लॉट",
    "detail.propertyIn": "{location} में प्रॉपर्टी",
    "detail.newProjectsIn": "{location} में नए प्रोजेक्ट",
    "detail.readyMoveIn": "{location} में रहने के लिए तैयार प्रॉपर्टी",
    "detail.propertyRohtak": "रोहतक में प्रॉपर्टी",
    "detail.flatsRohtak": "रोहतक में फ्लैट",
    "detail.houseRohtak": "रोहतक में बिक्री के लिए मकान",
    "detail.villaRohtak": "रोहतक में विला",
    "detail.readyFlatsRohtak": "रोहतक में रहने के लिए तैयार फ्लैट",
    "detail.resaleFlatsRohtak": "रोहतक में रीसेल फ्लैट",
    "detail.nearbyProjects": "नज़दीकी प्रोजेक्ट",
    "detail.disclaimer": "अस्वीकरण:",
    "detail.disclaimerCopy":
      "Arjun Buildtech ने RERA पंजीकरण की आवश्यकता की जाँच करने का प्रयास किया है। हालांकि, विज्ञापनदाता का दावा है कि ऐसे पंजीकरण की आवश्यकता नहीं है। उपयोगकर्ता कृपया ध्यान दें...",
    "detail.readMore": "और पढ़ें",
    "inquiryPopup.title": "त्वरित पूछताछ:",
    "inquiryPopup.company": "अर्जुन बिल्डटेक",
    "inquiryPopup.name": "* आपका नाम",
    "inquiryPopup.phone": "* आपका मोबाइल नंबर",
    "inquiryPopup.email": "* आपकी ईमेल आईडी",
    "inquiryPopup.query": "आपका प्रश्न",
    "inquiryPopup.send": "पूछताछ भेजें",
    "inquiryPopup.contactPerson": "संपर्क व्यक्ति",
    "inquiryPopup.contactName": "परवीन गहलावत",
    "inquiryPopup.addressLabel": "पता",
    "inquiryPopup.address": "G74P, सेक्टर-27, रोहतक, हरियाणा",
    "inquiryPopup.mobileLabel": "मोबाइल नं.",
    "inquiryPopup.emailLabel": "ईमेल आईडी",
    "inquiryPopup.received": "अनुरोध प्राप्त हुआ",
    "inquiryPopup.followup": "हमारे विशेषज्ञ जल्द ही आपसे संपर्क करेंगे।",
    "inquiryPopup.done": "पूर्ण",
    "emiCalc.pageTitle": "EMI कैलकुलेटर | अर्जुन बिल्डटेक",
    "emiCalc.title": "EMI कैलकुलेटर",
    "emiCalc.loanAmount": "ऋण राशि (रु.)",
    "emiCalc.interestRate": "ब्याज दर (%)",
    "emiCalc.loanPeriod": "ऋण अवधि (वर्ष)",
    "emiCalc.emi": "समान मासिक किस्त (EMI)",
    "emiCalc.calculate": "गणना करें",
    "emiCalc.clear": "साफ़ करें",
    "emiCalc.hotProperties": "हॉट प्रॉपर्टीज़",
    "emiCalc.guideTitle": "इस EMI कैलकुलेटर का उपयोग कैसे करें?",
    "emiCalc.guide1":
      "रुपये में वह कुल ऋण राशि दर्ज करें जो आप उधार लेना चाहते हैं।",
    "emiCalc.guide2": "लागू ब्याज दर (वार्षिक प्रतिशत) दर्ज करें।",
    "emiCalc.guide3": "ऋण अवधि या कार्यकाल वर्षों में दर्ज करें।",
    "emiCalc.guide4":
      "अपनी अनुमानित समान मासिक किस्त (EMI) देखने के लिए 'गणना करें' बटन पर क्लिक करें।",
    "emiCalc.guide5":
      "कैलकुलेटर को रीसेट करने और विभिन्न मूल्यों को आज़माने के लिए 'साफ़ करें' बटन का उपयोग करें।",
    "emiBanner.title": "अपने संपत्ति निवेश की योजना बनाएं",
    "emiBanner.subtitle":
      "अपनी मासिक किश्तों का तुरंत अनुमान लगाने के लिए हमारे आसान EMI कैलकुलेटर का उपयोग करें।",
    "emiBanner.button": "अब EMI की गणना करें",
    "tools.title": "सलाह और उपकरण",
    "tools.emiTitle": "EMI कैलकुलेटर",
    "tools.emiDesc": "जानें कि आपको अपने ऋण पर हर महीने कितना भुगतान करना होगा",
    "tools.homeLoanTitle": "सर्वश्रेष्ठ होम लोन ऑफ़र",
    "tools.homeLoanDesc":
      "विशेष रूप से आपके प्रोफ़ाइल के लिए तैयार किए गए सर्वोत्तम बैंक ऑफ़र प्राप्त करें",
    "tools.interiorsTitle": "इंटीरियर बजट अनुमानक",
    "tools.interiorsDesc":
      "अपने घर के पूर्ण/आंशिक इंटीरियर का काम कराने की लागत जानें",
    "tools.ratesTitle": "दरें और रुझान",
    "tools.ratesDesc":
      "अपने शहर में संपत्ति की दरों और रुझानों के बारे में सब कुछ जानें",
    "tools.areaDesc":
      "भूमि क्षेत्र को विभिन्न इकाइयों से वर्ग फुट में आसानी से बदलें",
    "tools.viewNow": "अभी देखें",
    "tools.pageTitle":
      "महत्वपूर्ण संपत्ति उपकरण और कैलकुलेटर | अर्जुन बिल्डटेक",
    "tools.pageMetaDesc":
      "अर्जुन बिल्डटेक के साथ EMI कैलकुलेटर, होम लोन ऑफ़र, इंटीरियर बजट अनुमानक और संपत्ति दरें और रुझान सहित महत्वपूर्ण रियल एस्टेट टूल तक पहुंचें।",
    "tools.pageHeading": "रियल एस्टेट सलाह और उपकरण",
    "tools.pageSubheading":
      "मुफ़्त रियल एस्टेट टूल के हमारे सुइट के साथ संपत्ति संबंधी सोच-समझकर निर्णय लें। अपनी EMI की गणना करें, होम लोन ऑफ़र की जांच करें, इंटीरियर लागत का अनुमान लगाएं और संपत्ति दरों और रुझानों को ट्रैक करें।",
    "areaCalc.pageTitle": "क्षेत्र परिवर्तक | अर्जुन बिल्डटेक",
    "areaCalc.title": "क्षेत्र परिवर्तक",
    "areaCalc.header": "स्क्वायर फीट में क्षेत्र रूपांतरण",
    "areaCalc.enterArea": "क्षेत्र दर्ज करें :",
    "areaCalc.selectUnit": "इकाई चुनें :",
    "areaCalc.sqFeets": "वर्ग फीट",
    "areaCalc.calculate": "गणना करें",
    "areaCalc.clear": "साफ़ करें",
    "card.contactAgent": "एजेंट से संपर्क करें",
    "card.viewPhone": "फोन नंबर देखें",
    "enquiry.fillForm": "नीचे पूछताछ फॉर्म भरें",
    "enquiry.sendForThis": "क्या आप इस संपत्ति के लिए पूछताछ भेजना चाहते हैं?",
    "enquiry.nameLabel": "नाम",
    "enquiry.emailLabel": "ईमेल",
    "enquiry.phoneLabel": "फ़ोन / मोबाइल",
    "enquiry.phonePlaceholder": "मोबाइल नंबर",
    "enquiry.descLabel": "विवरण",
    "enquiry.submit": "जमा करें",
    "contactBlock.title": "अर्जुन बिल्डटेक से संपर्क करें",
    "contactBlock.subtitle": "हमें सीधे कॉल करें",
    "contactBlock.callNow": "अभी कॉल करें",
    "contactBlock.share": "प्रॉपर्टी शेयर करें",
    "card.sendEnquiry": "पूछताछ भेजें",
  },
};

const getInitialLanguage = () => {
  try {
    const savedLanguage = localStorage.getItem("arjun-buildtech-language");
    if (savedLanguage === "en" || savedLanguage === "hi") return savedLanguage;
  } catch {
    // Storage can be unavailable in private browsing contexts.
  }

  return navigator.language?.toLowerCase().startsWith("hi") ? "hi" : "en";
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    document.documentElement.lang = language;
    try {
      localStorage.setItem("arjun-buildtech-language", language);
    } catch {
      // Language switching still works for the current visit.
    }
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key, english = key, values = {}) => {
        const text = translations[language][key] ?? english;
        return Object.entries(values).reduce(
          (result, [name, value]) => result.replaceAll(`{${name}}`, value),
          text,
        );
      },
    }),
    [language],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}
